name: CI

on:
  push:
    branches: [ main, staging, production ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    env:
      key: ${GITHUB_REF##*/}
      key2: ${{ github.event.deployment.environment }} 

    environment: 
#       if: github.ref == 'refs/heads/main'
      name: main
#     if: github.ref == 'refs/heads/staging'
#     name: staging
#         if: github.ref == 'refs/heads/production'
#          name: production
    

    steps:
      - name: Set env to main
        if: endsWith(github.ref, '/main')
        run: |
          echo "ENVIRONMENT=main" >> $GITHUB_ENV
      - name: Set env to staging
        if: endsWith(github.ref, '/staging')
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/production')
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "i'm at ${GITHUB_REF##*/}"
      - name: Run with secrets
        shell: bash
        run: echo "${{ secrets.TEST_KEY }} ${{ env.key2 }}"
      - name: Run with secrets v2
        shell: bash
        run: echo ${{ secrets.PROD_KEY }}
        env:
          key: ${GITHUB_REF##*/}
