name: CI

on:
  push:
    branches: [ main, staging, production ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: 
      name: "${{ GITHUB_REF##*/ }}"
    
    env:
      key: ${GITHUB_REF##*/}
      
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "i'm at ${GITHUB_REF##*/}"
      - name: Run with secrets
        shell: bash
        run: echo "${{ secrets.TEST_KEY }} ${{ env.key }}"
