name: CI

on:
  push:
    branches: [ main, staging, production ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    env:
      key: ${GITHUB_REF##*/}

    
    if: github.ref == 'refs/heads/main'
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "i'm at ${GITHUB_REF##*/}"
      - name: Run with secrets
        shell: bash
        run: echo "${{ secrets.TEST_KEY }} ${{ env.key }}"
      - name: Run with secrets v2
        shell: bash
        run: echo ${{ secrets.PROD_KEY }}
        env:
          key: ${GITHUB_REF##*/}
