name: CI

on:
  push:
    branches: [ main, staging, production ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: 
      name: ${GITHUB_REF##*/}
      
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "i'm at ${GITHUB_REF##*/}"
      - name: Run with secrets
        shell: bash
        run: echo "${{ secrets.TEST_KEY }} ${{ env.key }}"
      - name: Run with secrets v2
        shell: bash
        run: echo "$key"
        env:
          key: "secrets.${GITHUB_REF##*/}_TEST_KEY"
