name: CI

on:
  push:
    branches: [ main, staging, production ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    env:
      key: ${GITHUB_REF##*/}
      key2: ${{github.ref}}

    environment: 
#       if: github.ref == 'refs/heads/main'
      name: ${{github.ref}##*/}
#       elif: github.ref == 'refs/heads/staging'
#       name: staging
#       elif: github.ref == 'refs/heads/production'
#       name: ${{ github.event.deployment.environment }}
    

    steps:
      - uses: actions/checkout@v2
      - name: Run with secrets
        shell: bash
        run: echo "${{ secrets.TEST_KEY }} ${{ env.key2 }}"
      - name: Run with secrets v2
        shell: bash
        run: echo ${{ secrets.PROD_KEY }}
